config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    root 'admin_panel#index'
  end
  authenticated :user, ->(user) { !user.admin? } do
    # root 'user_panel#index'
  end
  root to: 'home#index'
  get '/dashboard',to: "user_panel#index", as: :user_panel
  get 'profile',to: "user_panel#profile",as: :profile
  get 'top_up',to: "user_panel#top_up",as: :top_up
  get 'invites',to: "user_panel#invites",as: :user_invites
  

  resources :leadership_surveys,only: [:new,:create] do
    resources :logbooks
    resources :responses,:controller => "submissions",only: [:new,:create]
    get 'summary'
  end

  resources :responses,:controller => "submissions",except: [:new,:create] do
    get :results
  end
  

  post 'start_survey',to: "leadership_surveys#start_survey",as: :start_survey
  get 'leadership_assessment/:id',to: "leadership_surveys#leadership_survey",as: :user_survey
  
  # get 'leadership_assessment/:id/results',to: "leadership_surveys#leadership_results",as: :user_survey_results
  
  get 'leadership_assessment/:id/invitees',to: "leadership_surveys#invitees",as: :survey_invitees
  get 'leadership_assessments',to: "leadership_surveys#leadership_tests",as: :user_tests
  post 'invite_user',to: "leadership_surveys#invite_user", as: :invite_user
  delete '/users/:id/destroy', to: 'leadership_surveys#destroy', as: :destroy_test

  # get 'payment',to: "user_panel#payment",as: :payment
  post 'payment',to: "user_panel#payment",as: :payment

  get 'admin_panel',to: 'admin_panel#index',as: :admin_panel
  get 'admin_panel/users',as: :admin_users
  get 'admin_panel/questionnaires',as: :admin_questionnaires
  get 'admin_panel/edit_intro',as: :admin_edit_intro
  post 'edit_intro',to: "admin_panel#edit_intro_save",as: :admin_edit_intro_save

  devise_for :users,:controllers => { sessions: 'users/sessions',registrations: 'users/registrations',passwords: 'users/passwords',invitations: 'users/invitations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:edit,:update]

  # get 'personal_logbook', to: 'users#logbook',as: :logbook
  # put 'personal_logbook', to: 'users#save_logbook',as: :save_logbook

  post 'stripe-webhooks',to: 'home#webhooks'

  root 'home#index'
  get 'design', to: 'home#design', as: 'design'

  # Excel Upload Feature
  post '/bulk_users', to: 'admin_panel#bulk_users_upload',
                      as: :bulk_users_upload

  # Payment Feature
  resources :variables

  # Locale Handling
  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    # Questionnaires
    resources :questionnaires
    # Dimensions
    resources :dimensions
    # Questions
    resources :questions
  # end
  # get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  # get '', to: redirect("/#{I18n.default_locale}")
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource class: false
  
  def index
    @users = User.where.not(id: current_user.id)
    @questionnaires = Questionnaire.all
  end

  def users
    @users = User.where.not(id: current_user.id)
  end

  def questionnaires
  	@questionnaires = Questionnaire.all.includes(:dimensions)
  end

  def edit_intro_save
    # @questionnaires

    # @intro = Variable.find_or_initialize_by(name: "INTRODUCTION")
    # params[:questionnaire].each do |k,v|
    #   # byebug
    #   Questionnaire.find_by_id(k)&.update!(intro_text: v[:intro_text])
    # end
    @success = Questionnaire.update(params[:questionnaire].keys, params[:questionnaire].values)
    # redirect_to request.referer,notice: "Text Updated"

    # @success = Questionnaire.update_all([{id: 1,intro_text: '123'},{id: 2,intro_text: '321'}])
    # @intro.description = params[:text]
    # @success = @intro.save!
  end

  def bulk_users_upload
    return unless params[:user].present?

    response = Admin::BulkUsersUpload.call(
      current_user: current_user,
      user_excel_file_params: user_excel_file_params
    )
    if response[:success] == true
      redirect_to admin_users_path, notice: 'Bulk Users Added Successfully'
    else
      redirect_to admin_users_path, alert: "Error #{response[:error]}"
    end
  end

  def user_excel_file_params
    params.require(:user).permit(:excel_file)
  end
end

app/views/admin_panel/_edit_intro_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="edit_intro" tabindex="-1" role="dialog" aria-labelledby="edit_introLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <p class="modal-title text-5 font-weight-bold mb-0" id="edit_introLabel">Introductory Paragraph</p>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with url: admin_edit_intro_save_path do |form| %>
        <div class="modal-body">
          <% @questionnaires.each do |q| %>
            <label class="mt-2"> <%= q.name %>  </label>
            <%= fields_for "questionnaire[]", q do |questionnaire_fields| %>
              <%= questionnaire_fields.text_area :intro_text, rows:3,class: 'form-control', value:"Below are some behaviours. Place indicate how frequent the person assessment shows them and how often he/she needs to show them in order to develop (do more or less) to a great leader." %>
            <% end %>
          <% end %>
            <%#= text_area_tag "text",Variable.find_by_name("INTRODUCTION")&.description,required: true,class: "form-control" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= form.submit "Submit",id: "paragraph_submit",class: "btn btn-primary",data: {disable_with: "Submitting"} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin_panel/edit_intro.js.erb
$("#edit_intro").modal("show");

app/views/admin_panel/edit_intro_save.js.erb
<% if @success%>
	toastr.success("Saved successfully!")
<% else %>
	toastr.error("Something went wrong. Please try again!")
<% end %>
$("#edit_intro").modal("hide");

app/views/admin_panel/index.html.erb
<div class="container-fluid container-admin">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="card card-admin">
          <div class="card-body">
            <h3 class="text-primary mb-4 text-center"> Dashboard </h3>
            <div class="row">
              <div class="col-12">
                <a class="dashboard-side-link active" href="<%= admin_users_path %>"><i class="fas fa-users"></i><span>Users</span></a>
                <a class="dashboard-side-link" href="<%= questionnaires_path %>"><i class="far fa-question-circle"></i><span>Questionnaires</span></a>
                <a class="dashboard-side-link" href="<%= dimensions_path %>"><i class="fas fa-arrows-alt"></i><span>Dimensions</span></a>
                <a class="dashboard-side-link" href="<%= questions_path %>"><i class="fas fa-question-circle"></i><span>Questions</span></a>
                <a class="dashboard-side-link" href="<%= variables_path %>"><i class="fas fa-list"></i><span>Variables</span></a>
                <!--<a class="dashboard-side-link" data-remote="true" href="<%= admin_edit_intro_path %>"><i class="fas fa-list"></i><span>Introductory Paragraph</span></a>-->
                <a class="dashboard-side-link" href="<%= destroy_user_session_path %>" data-method="delete"><i class="fas fa-sign-out-alt"></i><span>Log Out</span></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-9 mt-4 mt-lg-0">
        <h5 class="mb-4">Statistics</h5>
        <div class="row card-stats">
          <div class="col-md-4 col-sm-6">
            <%= link_to admin_users_path do %>
              <div class="card text-center">
                <h4>TOTAL USERS</h4>
                <h2><%= @users.size %></h2>
              </div>
            <% end %>
          </div>
          <div class="col-md-4 col-sm-6">
            <%= link_to questionnaires_path do %>
              <div class="card text-center">
                <h4>QUESTIONNAIRES</h4>
                <h2><%= Questionnaire.all.size %></h2>
              </div>
            <% end %>
          </div>
          <div class="col-md-4 col-sm-6">
            <%= link_to dimensions_path do %>
              <div class="card text-center">
                <h4>TOTAL DIMENSIONS</h4>
                <h2><%= Dimension.all.size %></h2>
              </div>
            <% end %>
          </div>
          <div class="col-md-4 col-sm-6">
            <%= link_to questions_path do %>
              <div class="card text-center">
                <h4>TOTAL QUESTIONS</h4>
                <h2><%= Question.all.size %></h2>
              </div>
            <% end %>
          </div>
          <div class="col-md-4 col-sm-6">
            <%= link_to variables_path do %>
              <div class="card text-center">
                <h4>TOTAL VARIABLES</h4>
                <h2><%= Variable.all.size %></h2>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%#= render "edit_intro_modal" %>

app/views/admin_panel/questionnaires.html.erb
<div class="container container-admin">
	<ul class="nav nav-tabs nav-tabs-default nav-tabs-centered" id="tabCentered" role="tablist">
		<% @questionnaires.each_with_index do |questionnaire,index| %>
			<li class="nav-item">
				<a class="text-4 nav-link <%= 'active' if index == 0 %>" id="tab<%= questionnaire.id %>" data-toggle="tab" href="#tab<%= questionnaire.id %>s" role="tab" aria-controls="tab<%= questionnaire.id %>s" aria-expanded="true"><%= questionnaire.name%></a>
			</li>
		<% end %>
	</ul>
	<div class="tab-content" id="tabCenteredContent">
		<% @questionnaires.each_with_index do |questionnaire,index| %>
			<div class="tab-pane fade pt-4 pb-4 <%= 'show active' if index == 0 %>" id="tab<%= questionnaire.id %>s" role="tabpanel" aria-labelledby="tab<%= questionnaire.id %>">
				<div class="row mb-4 align-items-center">
					<div class="col-lg-6 text-center text-lg-left">
						<h5 class="mb-3 mb-lg-0">Dimensions of <%= questionnaire.name %></h5>
					</div>
					<div class="col-lg-6 text-center text-lg-right">
						<%= link_to "Questions in this questionnaire",questions_path(questionnaire: questionnaire.id), class:"btn btn-primary mb-2 mb-lg-0" %>
						<%= link_to "Add new dimension",new_dimension_path, class:"btn btn-primary mb-2 mb-lg-0" %>
					</div>
				</div>
				<div class="table-responsive table-users">
					<table class="table table-bordered">
						<thead>
							<tr>
								<th width="80%">Dimension Name</th>
								<th colspan="2">
									Actions
								</th>
							</tr>
						</thead>
						<tbody>
							<% questionnaire.dimensions.each do |dimension|%>
								<tr>
									<td width="80%"><%= dimension.name %></td>
									<td class="action-links text-center"><%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_dimension_path(dimension) %></td>
									<td class="action-links text-center"><%= link_to '<i class="fas fa-trash-alt text-danger"></i>'.html_safe, dimension, method: :delete, data: { confirm: 'Are you sure?' } %></td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/admin_panel/users.html.erb
<div class="container-fluid container-admin">
  <div class="card mb-5">
    <div class="card-body text-center px-4">
      <h5 class="mb-3">Bulk Users upload</h5>
      <p class="mark py-2 d-inline-block px-sm-5">File should be in OpenDocument Format, also known as the .ODS Spreadsheet. This Format is available for Microsoft Excel.</p>
      <br/>
      <%= link_to 'Downlaod Sample File', root_url + 'Users.ods', { target: '_blank', class:"btn btn-primary btn-sm mb-4" }  %>
      <%= form_with url: '/bulk_users', scope: 'user', local: true do |form| %>
        <%= form.file_field :excel_file, class:"form-control w-500 mx-auto", required: true %>
        <%= form.submit 'Upload File', class:"btn btn-primary mt-4" %>
      <% end %>
    </div>
  </div>
  <h5 class="mb-4 pt-2">All Users</h5>
  <div class="table-responsive table-users table-datatable">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Email</th>
          <th>Age</th>
          <th>Gender</th>
          <th>Country</th>
          <th>Highest Education</th>
          <th>Phone Number</th>
          <th>Organization Name</th>
          <th>Corporate User</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= user.age.present? ? user.age : 'Not Provided' %></td>
            <td><%= user.gender.present? ? user.gender : 'Not Provided' %></td>
            <td><%= user.country.present? ? user.country : 'Not Provided' %></td>
            <td><%= user.highest_education.present? ? user.highest_education : 'Not Provided' %></td>
            <td><%= user.phone_number.present? ? user.phone_number : 'Not Provided' %></td>
            <td><%= user.organization_name.present? ? user.organization_name : 'Not Provided' %></td>
            <td><%= user.corporate_user %></td>
          </tr>
        <% end%>
      </tbody>
    </table>
  </div>
</div>