config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    root 'admin_panel#index'
  end
  authenticated :user, ->(user) { !user.admin? } do
    # root 'user_panel#index'
  end
  root to: 'home#index'
  get '/dashboard',to: "user_panel#index", as: :user_panel
  get 'profile',to: "user_panel#profile",as: :profile
  get 'top_up',to: "user_panel#top_up",as: :top_up
  get 'invites',to: "user_panel#invites",as: :user_invites
  

  resources :leadership_surveys,only: [:new,:create] do
    resources :logbooks
    resources :responses,:controller => "submissions",only: [:new,:create]
    get 'summary'
  end

  resources :responses,:controller => "submissions",except: [:new,:create] do
    get :results
  end
  

  post 'start_survey',to: "leadership_surveys#start_survey",as: :start_survey
  get 'leadership_assessment/:id',to: "leadership_surveys#leadership_survey",as: :user_survey
  
  # get 'leadership_assessment/:id/results',to: "leadership_surveys#leadership_results",as: :user_survey_results
  
  get 'leadership_assessment/:id/invitees',to: "leadership_surveys#invitees",as: :survey_invitees
  get 'leadership_assessments',to: "leadership_surveys#leadership_tests",as: :user_tests
  post 'invite_user',to: "leadership_surveys#invite_user", as: :invite_user
  delete '/users/:id/destroy', to: 'leadership_surveys#destroy', as: :destroy_test

  # get 'payment',to: "user_panel#payment",as: :payment
  post 'payment',to: "user_panel#payment",as: :payment

  get 'admin_panel',to: 'admin_panel#index',as: :admin_panel
  get 'admin_panel/users',as: :admin_users
  get 'admin_panel/questionnaires',as: :admin_questionnaires
  get 'admin_panel/edit_intro',as: :admin_edit_intro
  post 'edit_intro',to: "admin_panel#edit_intro_save",as: :admin_edit_intro_save

  devise_for :users,:controllers => { sessions: 'users/sessions',registrations: 'users/registrations',passwords: 'users/passwords',invitations: 'users/invitations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:edit,:update]

  # get 'personal_logbook', to: 'users#logbook',as: :logbook
  # put 'personal_logbook', to: 'users#save_logbook',as: :save_logbook

  post 'stripe-webhooks',to: 'home#webhooks'

  root 'home#index'
  get 'design', to: 'home#design', as: 'design'

  # Excel Upload Feature
  post '/bulk_users', to: 'admin_panel#bulk_users_upload',
                      as: :bulk_users_upload

  # Payment Feature
  resources :variables

  # Locale Handling
  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    # Questionnaires
    resources :questionnaires
    # Dimensions
    resources :dimensions
    # Questions
    resources :questions
  # end
  # get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  # get '', to: redirect("/#{I18n.default_locale}")
end

app/models/questionnaire.rb
# frozen_string_literal: true

# :Questionnarie Class for handling Associations and Settings:
class Questionnaire < ApplicationRecord
  has_many :dimensions, dependent: :destroy
  # has_and_belongs_to_many :questionnaires

  has_many :questions, dependent: :destroy

  # Globalize
  translates :name, :intro_text
end

app/controllers/questionnaires_controller.rb
# frozen_string_literal: true

# :Questionnaires Controller for managing questionnaires actions:
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: %i[show edit update destroy]
  load_and_authorize_resource
  def index
    @questionnaires = Questionnaire.all
  end

  def new
    @questionnaire = Questionnaire.new
  end

  def show; end

  def create
    @questionnaire = Questionnaire.new(questionnaire_params)
    if @questionnaire.save
      redirect_to @questionnaire, notice: 'Questionnaire was successfully created.'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @questionnaire.update(questionnaire_params)
      redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    return unless @questionnaire.destroy

    redirect_to questionnaires_path, notice: 'Questionnaire was successfully deleted.'
  end

  private

  def set_questionnaire
    @questionnaire = Questionnaire.find(params[:id])
  end

  def questionnaire_params
    params.require(:questionnaire).permit(:name, :intro_text, :priority)
  end
end

app/views/questionnaires/_form.html.erb
<%= form_with(model: questionnaire, local: true) do |form| %>
  <% if questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>
      <ul>
      <% questionnaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <% if I18n.locale != :en && form&.object&.id.present? %>
      <% Globalize.with_locale(:en) do %>
        <p class='mark text-center'>English: <%= form.object.name %><p>
      <% end %>
    <% end %>
    <%= form.text_field :name, required: true,class: "form-control login-form", placeholder: "Name" %>
  </div>
  <div class="form-group">
    <% if I18n.locale != :en && form&.object&.id.present? %>
      <% Globalize.with_locale(:en) do %>
        <p class='mark text-center'>English: <%= form.object.intro_text %><p>
      <% end %>
    <% end %>
    <%= form.text_area :intro_text, class: 'form-control login-form', placeholder: "Intro Text" %>
  </div>
  <div class="form-group">
    <%= form.number_field :priority, step: 0, class: 'form-control login-form', placeholder: "Set Priority" %>
  </div>
  <%= form.hidden_field :locale, value: params[:locale] %>
  <div class="actions mt-3">
    <%= form.submit class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/questionnaires/edit.html.erb
<div class="container-fluid container-top">
  <div class="container container-signin container-sign px-4">
    <div class="modal-login-body">
      <h3 class="text-center mb-4">Editing Questionnaire</h3>
      <%= render 'form', questionnaire: @questionnaire %>
    </div>
  </div>
</div>

app/views/questionnaires/index.html.erb
<div class="container container-admin">
  <div class="container">
    <div class="row mb-4 align-items-center">
      <div class="col-md-6 text-center text-md-left">
        <h5 class="mb-3 mb-md-0">Questionnaires</h5>
      </div>
      <div class="col-md-6 text-center text-md-right">
        <%= link_to 'New Questionnaire', new_questionnaire_path, class:"btn btn-primary" %>
      </div>
    </div>
  <div class="table-responsive table-users">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Intro Text</th>
          <th>Proiority</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @questionnaires.each do |questionnaire| %>
        <tr>
          <td><%= questionnaire.name %></td>
          <td><%= questionnaire.intro_text %></td>
          <td><%= questionnaire.priority %></td>
          <td class="action-links text-center"><%= link_to '<i class="fas fa-eye"></i>'.html_safe, questionnaire %></td>
          <td class="action-links text-center"><%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_questionnaire_path(questionnaire) %></td>
          <td class="action-links text-center"><%= link_to '<i class="fas fa-trash-alt text-danger"></i>'.html_safe, questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/questionnaires/new.html.erb
<div class="container-fluid container-top">
  <div class="container container-signin container-sign px-4">
    <div class="modal-login-body">
      <h3 class="text-center mb-4">New Questionnaire</h3>
      <%= render 'form', questionnaire: @questionnaire %>
    </div>
  </div>
</div>

app/views/questionnaires/show.html.erb
<div class="container-fluid container-admin">
  <div class="container container-signin container-sign px-4">
    <div class="modal-login-body">
      <p>
        <strong>Name</strong><br/>
        <%= @questionnaire.name %>
      </p>
      <p>
        <strong>Intro Text</strong><br/>
        <%= @questionnaire.intro_text %>
      </p>
      <p>
        <strong>Priority</strong><br/>
        <%= @questionnaire.priority %>
      </p>
      <center>
      <%= link_to 'Edit', edit_questionnaire_path(@questionnaire), class:"btn btn-primary btn-lg mb-3" %> 
      <%= link_to 'Back', questionnaires_path, class:"btn btn-secondary btn-lg mb-3" %>
    </center>
    </div>
  </div>
</div>