config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    root 'admin_panel#index'
  end
  authenticated :user, ->(user) { !user.admin? } do
    # root 'user_panel#index'
  end
  root to: 'home#index'
  get '/dashboard',to: "user_panel#index", as: :user_panel
  get 'profile',to: "user_panel#profile",as: :profile
  get 'top_up',to: "user_panel#top_up",as: :top_up
  get 'invites',to: "user_panel#invites",as: :user_invites
  

  resources :leadership_surveys,only: [:new,:create] do
    resources :logbooks
    resources :responses,:controller => "submissions",only: [:new,:create]
    get 'summary'
  end

  resources :responses,:controller => "submissions",except: [:new,:create] do
    get :results
  end
  

  post 'start_survey',to: "leadership_surveys#start_survey",as: :start_survey
  get 'leadership_assessment/:id',to: "leadership_surveys#leadership_survey",as: :user_survey
  
  # get 'leadership_assessment/:id/results',to: "leadership_surveys#leadership_results",as: :user_survey_results
  
  get 'leadership_assessment/:id/invitees',to: "leadership_surveys#invitees",as: :survey_invitees
  get 'leadership_assessments',to: "leadership_surveys#leadership_tests",as: :user_tests
  post 'invite_user',to: "leadership_surveys#invite_user", as: :invite_user
  delete '/users/:id/destroy', to: 'leadership_surveys#destroy', as: :destroy_test

  # get 'payment',to: "user_panel#payment",as: :payment
  post 'payment',to: "user_panel#payment",as: :payment

  get 'admin_panel',to: 'admin_panel#index',as: :admin_panel
  get 'admin_panel/users',as: :admin_users
  get 'admin_panel/questionnaires',as: :admin_questionnaires
  get 'admin_panel/edit_intro',as: :admin_edit_intro
  post 'edit_intro',to: "admin_panel#edit_intro_save",as: :admin_edit_intro_save

  devise_for :users,:controllers => { sessions: 'users/sessions',registrations: 'users/registrations',passwords: 'users/passwords',invitations: 'users/invitations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:edit,:update]

  # get 'personal_logbook', to: 'users#logbook',as: :logbook
  # put 'personal_logbook', to: 'users#save_logbook',as: :save_logbook

  post 'stripe-webhooks',to: 'home#webhooks'

  root 'home#index'
  get 'design', to: 'home#design', as: 'design'

  # Excel Upload Feature
  post '/bulk_users', to: 'admin_panel#bulk_users_upload',
                      as: :bulk_users_upload

  # Payment Feature
  resources :variables

  # Locale Handling
  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    # Questionnaires
    resources :questionnaires
    # Dimensions
    resources :dimensions
    # Questions
    resources :questions
  # end
  # get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  # get '', to: redirect("/#{I18n.default_locale}")
end

app/controllers/user_panel_controller.rb
class UserPanelController < ApplicationController
	before_action :authenticate_user!,except: :leadership_survey
	def payment
		@amount = (params[:amount].to_f * 100).to_i
		@intent = Stripe::PaymentIntent.create({
	        amount: @amount,
	        currency: 'usd',
	        payment_method_types: ['card'],
	        description: current_user.email
	    })

	    respond_to do |format|
	    	format.html {}
	    	format.js {}
	    end
	end

	def invites
		@tests = current_user.invites
	end
	
	private
		
end

app/views/user_panel/_stripe_card.html.erb
<input id="cardholder-email" type="text" placeholder="Card Holder Name" class="form-control login-form" required="true">
<div id="card-element" style="margin: 30px 0px;"></div>
<button id="card-button" data-secret="<%= @intent.client_secret %>" class="btn btn-primary btn-lg btn-block mb-3 btn-submit">Submit Payment</button>

app/views/user_panel/index.html.erb
<div class="container container-dashboard">
  <div class="row">
    <div class="col-12">
      <div class="user-header-bg">
        <div class="user-header">
          <div class="row align-items-center">
            <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-5">
              <img src="<%= current_user.profile_pic%>" width="155" class="avatar-img">
            </div>
            <div class="col-xl-10 col-lg-9 col-md-8 col-sm-6 col-7">
              <div class="row">
                <div class="col-12">
                  <h2 class="text-primary mb-3"> <%= current_user.name%> </h2>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <a href="<%= profile_path%>" class="btn btn-primary btn-lg mt-2 px-sm-4">Edit Profile</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="p-50 bg-white user-body">
        <div class="row mb-3 mb-md-0 align-items-center">
          <div class="col-md-6 col-lg-3 text-md-right text-lg-left text-center text-lg-left text-center mb-3 mb-md-0">
            <h3 class="font-weight-bold">assessments</h3>
          </div>
          <div class="col-md-6 col-lg-3 text-lg-left text-center mb-3 mb-md-0">
            <a href="<%= user_tests_path %>" class="btn btn-primary">Leadership Tests</a>
          </div>
          <div class="col-md-12 col-lg-6 text-lg-right text-center mb-3 mb-md-0">
            <h3 class="align-middle font-weight-bold mb-0 d-inline-block mr-4 mt-md-3 mt-xl-0"> Your Balance: <span class="text-primary letter-spacing-0"><%= humanized_money_with_symbol(current_user.balance)%></span></h3>
            <a href="<%= top_up_path %>" class="btn btn-primary mt-2 mt-sm-0 mt-md-3 mt-xl-0 mb-md-0">Top Up</a>
          </div>
        </div>
        <!--
        <div class="row row-user-fields">
          <div class="col-md-6">
            <div class="user-fields mb-3 mb-md-0">
              <span class="font-weight-bold">Name:</span>
              <span class="float-right"><%= current_user.name%></span>
            </div>
          </div>
          <div class="col-md-6">
            <div class="user-fields mb-3 mb-md-0">
              <span class="font-weight-bold">Email:</span>
              <span class="float-right"><%= current_user.email%></span>
            </div>
          </div>
        </div>
        -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_panel/invites.html.erb
<div class="container-fluid container-admin">
	<div class="container">
		<div class="row mb-4 align-items-center">
			<div class="col-lg-9 text-center text-lg-left">
				<h5 class="mb-3 mb-lg-0">You have been invited to these assessments</h5>
			</div>
			<div class="col-lg-3 text-center text-lg-right">
				<%= link_to "<i class='fas fa-plus mr-2 text-5'></i>new Assessment".html_safe,new_leadership_survey_path,remote: true,class: 'btn btn-primary mb-2 mb-lg-0' %>
			</div>
		</div>
		<div class="table-responsive table-users leadership-table">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th class="text-center">Assessment ID</th>
						<th class="text-center">Name</th>
						<th class="text-center">
							Actions
						</th>
					</tr>
				</thead>
				<tbody>
					<% @tests.each do |test| %>
						<tr id="test_<%= test.id %>">
							<td class="text-center"><%= test&.slug %></td>
							<td class="text-center"><%= test&.name %></td>
							<td class="action-links">
									<%#= link_to "<i class='fas fa-stream mr-2'></i>Continue Assessment".html_safe, user_survey_path(test&.slug), class:"btn btn-info btn-sm mr-3 mb-2 mb-lg-0" %>

									<% response = test.responses.where(user: current_user,user_id: current_user.id).first %>

									<% if response.present? %>

										<%= link_to "<i class='fas fa-stream mr-2'></i>#{response.completed ? "Assessment Completed": "Continue Assessment"}".html_safe, (response.completed ? "#": edit_response_path(response)),class:"btn #{response.completed ? "disabled": ""} btn-info btn-sm mr-3 mb-2 mb-lg-0" %>
									<% else %>
										<%= link_to "<i class='fas fa-stream mr-2'></i>Start Assessment".html_safe, new_leadership_survey_response_path(test), remote: true ,class:"btn btn-info btn-sm mr-3 mb-2 mb-lg-0" %>
									<% end %>
									

								<%#= link_to "<i class='fas fa-trash-alt mr-2'></i>Remove Assessment".html_safe, destroy_test_path(test.id), class:"btn btn-danger btn-sm mr-3 mb-2 mb-lg-0",method: :delete,remote: true %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<center><%#= paginate @tests %></center>
		</div>
	</div>
</div>

app/views/user_panel/payment.js.erb
// alert("<%= params[:amount]%>")
$(".payment").html("<%= j render 'stripe_card' %>");

var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

    var elements = stripe.elements();
    var cardElement = elements.create('card');
    cardElement.mount('#card-element');

    var cardholderEmail = "<%= current_user.email %>";
    var cardButton = document.getElementById('card-button');
    var clientSecret = cardButton.dataset.secret;

    cardButton.addEventListener('click', function(ev) {
      stripe.handleCardPayment(
        clientSecret, cardElement, {
          payment_method_data: {
            billing_details: {email: cardholderEmail}
          }
        }
      ).then(function(result) {
      if (result.error) {
      // Display error.message in your UI.
        toastr.error(result.error.message)
      } else {
        // The payment has succeeded. Display a success message.
        $(".payment").html("<p>$<%= params[:amount].to_i %> successfully added in your credit. </p><a href='<%= user_panel_path%>'> Go back to Dashboard.</a>");
      }
    });
  });

app/views/user_panel/profile.html.erb
<div class="container-fluid container-top">
	<div class="container container-signup container-sign">
		<div class="modal-login-body">
			<h3 class="text-center">Update Profile</h3>
			<hr/>
			<%= form_for(current_user) do |f| %>
				<div class="avatar-upload">
					<div class="avatar-edit">
						<%= f.file_field :profile_pic,id: "imageUpload", accept:"image/*" %>
						<label for="imageUpload"></label>
					</div>
					<div class="avatar-preview">
						<div id="imagePreview" style="background-image: url(<%= current_user.profile_pic %>);">
						</div>
					</div>
				</div>
				<div class="h6 lh-25 alert alert-warning"><strong>Privacy disclaimer:</strong> The data about age, gender, country, highest education and industry are for research purposes.</div>
				<div class="row">
					<div class="col-md-6 mt-3">
						<label for="user_name" class="mb-1 font-weight-bold">Name</label>
						<%= f.text_field :name, autofocus: true, required: true, placeholder: 'Enter Your Name', class: 'form-control login-form' %>
					</div>
					<div class="col-md-6 mt-3">
						<label for="user_surname" class="mb-1 font-weight-bold">Surname</label>
						<%= f.text_field :surname, required: true, placeholder: 'Enter Your Surname', class: 'form-control login-form' %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 mt-3">
						<label for="user_age" class="mb-1 font-weight-bold">Age</label>
						<%= f.number_field :age, step: 0, required: true, placeholder: 'Enter Your Age', class: 'form-control login-form' %>
					</div>
					<div class="col-md-6 mt-3">
						<label for="user_gender" class="mb-1 font-weight-bold">Gender</label>
						<%= f.select :gender, options_for_select([["Male", "Male"], ["Female", "Female"], ["Other", "Other"]], selected: current_user.gender), {include_blank: "Select Gender"}, { class: "form-control login-form", required: true } %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 mt-3">
						<label for="user_country" class="mb-1 font-weight-bold">Country</label>
						<%= f.text_field :country, required: true, placeholder: 'Enter Your Country', class: 'form-control login-form' %>
					</div>
					<div class="col-md-6 mt-3">
						<label for="user_highest_education" class="mb-1 font-weight-bold">Last Education</label>
						<%= f.text_field :highest_education, required: true, placeholder: 'Enter Your Last Education', class: 'form-control login-form' %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 mt-3">
						<label for="user_phone_number" class="mb-1 font-weight-bold">Phone Number</label>
						<%= f.number_field :phone_number, placeholder: 'Enter Your Phone Number', class: 'form-control login-form', required: true %>
					</div>
					<div class="col-md-6 mt-3">
						<label for="user_industry" class="mb-1 font-weight-bold">Industry</label>
						<%= f.select :industry ,options_for_select([["Aerospace", "Aerospace"], ["Agriculture", "Agriculture"], ["Pharmaceuticals", "Pharmaceuticals"], ["Software", "Software"], ["Construction", "Construction"], ["Education", "Education"]], selected: current_user.industry), {include_blank: "Select Industry"}, { class: "form-control login-form", required: true } %>
					</div>
				</div>
				<div class="col-md-6 px-0 mx-auto actions mt-4">
					<%= f.submit "Update", class: 'btn btn-primary btn-block mb-3' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/user_panel/top_up.html.erb
<div class="container-fluid container-top">
  <div class="container container-signin container-sign">
    <div class="modal-login-body">
      <div class="payment">
        <h3 class="text-center mb-3">Top Up</h3>
        <%= form_with url: payment_path do |form| %>
        
        <div class="form-group">
          <%= form.number_field :amount,step: "0.01",min: 0, placeholder: 'Enter Amount', class: 'form-control login-form', required: true %>
        </div>
        
        <div class="actions mt-3">
          <%= form.submit "Top Up", class: 'btn btn-primary btn-lg btn-block mb-3 btn-submit' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>